apiVersion: v1
kind: Service
metadata:
  name: {{ include "beego-app-edp-github-jira-int.fullname" . }}
  labels:
    {{- include "beego-app-edp-github-jira-int.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "beego-app-edp-github-jira-int.selectorLabels" . | nindent 4 }}
